

CREATE TABLE `bookWeb`.`MEMBER` (
  `CODE` INT NOT NULL,
  `ID` VARCHAR(45) NULL,
  `PASSWORD` VARCHAR(100) NULL,
  `EMAIL` VARCHAR(100) NULL,
  `PHONE` VARCHAR(45) NULL,
  `NICKNAME` VARCHAR(45) NULL,
  PRIMARY KEY (`CODE`));

CREATE TABLE `bookWeb`.`CATEGORY` (
  `CODE` INT NOT NULL,
  `CATEGORY` VARCHAR(45) NULL,
  PRIMARY KEY (`CODE`));

CREATE TABLE `SUB_CATEGORY` (
  `CODE` int NOT NULL,
  `CATEGORYCODE` int DEFAULT NULL,
  `SUB_CATEGORY` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`CODE`),
  KEY `CATEGORYCODE` (`CATEGORYCODE`),
  CONSTRAINT `sub_category_ibfk_1` FOREIGN KEY (`CATEGORYCODE`) REFERENCES `CATEGORY` (`CODE`)
) ;

CREATE TABLE `BOOK` (
  `CODE` int NOT NULL,
  `TITLE` varchar(100) DEFAULT NULL,
  `DETAIL` varchar(1000) DEFAULT NULL,
  `AUTHORITY` varchar(100) DEFAULT NULL,
  `SUBCATEGORY` int DEFAULT NULL,
  `PRICE` int DEFAULT NULL,
  `PUBLISHER` varchar(100) DEFAULT NULL,
  `DATE` datetime DEFAULT NULL,
  `IMAGE` varchar(1000) DEFAULT NULL,
  PRIMARY KEY (`CODE`),
  CONSTRAINT `book_ibfk_1` FOREIGN KEY (`CODE`) REFERENCES `SUB_CATEGORY` (`CODE`)
) ;